pub mod api;

pub use proxy::builder::AppStateBuilder;
pub use server::embedded::{EmbeddedGateway, start_embedded, start_embedded_with};
pub mod benchmark;
pub mod cache;
pub mod classifier;
pub mod config;
pub mod error;
pub mod experiment;
pub mod interop;
pub mod keys;
pub mod mcp;
pub mod models;
pub mod observability;
pub mod prompts;
pub mod providers;
pub mod proxy;
pub mod routing;
pub mod server;
pub mod types;

#[cfg(feature = "full")]
pub mod alerts;
#[cfg(feature = "full")]
pub mod billing;
#[cfg(feature = "full")]
pub mod compliance;
#[cfg(feature = "full")]
pub mod enterprise;
#[cfg(feature = "full")]
pub mod finetuning;
#[cfg(feature = "full")]
pub mod guardrails;
#[cfg(feature = "full")]
pub mod optimization;
pub mod waste;
#[cfg(feature = "full")]
pub mod workflows;
