#!/usr/bin/env bash

set -euxo pipefail

if [[ $# -gt 0 ]]; then
  echo "
  Usage: ${0##*/}
  Builds and installs Prism onto your system into ~/.local, making it available as ~/.local/bin/prism.

  Before running this you should ensure you have all the build dependencies installed with \`./script/linux\`.
  "
  exit 1
fi
export PRISM_CHANNEL=$(<ide/zed/RELEASE_CHANNEL)
export PRISM_UPDATE_EXPLANATION="You need to fetch and rebuild Prism in $(pwd)"
script/bundle-linux

arch="$(uname -m)"
archive="prism-linux-${arch}.tar.gz"
export PRISM_BUNDLE_PATH="${CARGO_TARGET_DIR:-target}/release/${archive}"
script/install.sh
