pub mod health;
pub mod metrics;
pub mod models;
pub mod openapi;

#[cfg(feature = "full")]
pub mod alerts;
#[cfg(feature = "full")]
pub mod aliases;
#[cfg(feature = "full")]
pub mod audit;
#[cfg(feature = "full")]
pub mod billing;
#[cfg(feature = "full")]
pub mod budgets;
#[cfg(feature = "full")]
pub mod config_reload;
#[cfg(feature = "full")]
pub mod interop;
#[cfg(feature = "full")]
pub mod keys;
#[cfg(feature = "full")]
pub mod mcp;
#[cfg(feature = "full")]
pub mod prompts;
#[cfg(feature = "full")]
pub mod routing;
#[cfg(feature = "full")]
pub mod stats;
#[cfg(feature = "full")]
pub mod workflows;
